services:
  mongodb:
    image: mongo:latest
    container_name: landing-pages-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - landing-pages-network

  mongo-express:
    image: mongo-express:latest
    container_name: landing-pages-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - landing-pages-network

volumes:
  mongodb_data:

networks:
  landing-pages-network:
    driver: bridge